server:
  port: 8888
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/vperezceNTTDATA/service-configuration
          searchPaths: service-configuration
          username: vperezceNTTDATA
          password: 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
          default-label: main
  security:
    user:
      name: root
      password: s3cr3t